# Generated by Django 3.0.14 on 2022-02-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='headset',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
